services:
  web:
    container_name: keyshift
    image: ghcr.io/helloworld44-89/keyshift:latest
    ports:
      - "5000:5000"
    volumes:
      - ./data/db:/app/instance
      - ./data/cron:/etc/cron.d
      - ./data/config:/app/app/config/file
    env_file:
      - .env